"""Markdown レポート生成"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from gh_trend_reporter.models import WeeklyAnalysis, WeeklyReport

logger = logging.getLogger(__name__)


class ReportGenerator:
    """WeeklyReport から Markdown レポートを生成する"""

    def __init__(self, *, reports_dir: Path | str = "./reports") -> None:
        self._reports_dir = Path(reports_dir)

    def render(self, report: WeeklyReport) -> str:
        """WeeklyReport を Markdown 文字列にレンダリングする"""
        analysis = report.analysis
        lines: list[str] = []

        # Frontmatter
        lines.append("---")
        lines.append(f'week: "{analysis.week_label}"')
        lines.append(
            f'period: "{analysis.period_start.isoformat()} 〜 {analysis.period_end.isoformat()}"'
        )
        lines.append(f'generated_at: "{report.generated_at.isoformat()}"')
        lines.append(f'model: "{report.model}"')
        lines.append(f"total_repos: {analysis.total_repos_collected}")
        lines.append("---")
        lines.append("")

        # Title
        lines.append(f"# GitHub Trending 週次レポート — {analysis.week_label}")
        lines.append("")

        # Highlights
        if analysis.highlights:
            lines.append("## 今週のハイライト")
            lines.append("")
            for hl in analysis.highlights:
                lines.append(f"- {hl}")
            lines.append("")

        # Language ranking
        if analysis.top_languages:
            lines.append("## 言語別ランキング")
            lines.append("")
            lines.append("| 順位 | 言語 | リポジトリ数 | 割合 |")
            lines.append("|------|------|------------|------|")
            for i, lang in enumerate(analysis.top_languages, 1):
                name = lang.get("language", "")
                count = lang.get("count", 0)
                pct = lang.get("percentage", 0.0)
                lines.append(f"| {i} | {name} | {count} | {pct}% |")
            lines.append("")

        # Category sections
        if analysis.categories:
            lines.append("## カテゴリ別分析")
            lines.append("")
            for cat in analysis.categories:
                lines.append(f"### {cat.category}")
                lines.append("")
                lines.append(cat.summary_ja)
                lines.append("")
                if cat.repos:
                    lines.append("**注目リポジトリ**")
                    lines.append("| リポジトリ |")
                    lines.append("|-----------|")
                    for repo_name in cat.repos:
                        lines.append(f"| {repo_name} |")
                    lines.append("")

        # New entries
        if analysis.new_entries:
            lines.append("## 新登場リポジトリ")
            lines.append("")
            lines.append(
                "先週の Trending には登場せず、今週新たに Trending 入りしたリポジトリ:"
            )
            lines.append("")
            lines.append("| リポジトリ |")
            lines.append("|-----------|")
            for entry in analysis.new_entries:
                lines.append(f"| {entry} |")
            lines.append("")

        # Week-over-week comparison
        if analysis.week_over_week:
            lines.append("## 先週との比較")
            lines.append("")
            lines.append(analysis.week_over_week)
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by gh-trend-reporter*")
        lines.append("")

        return "\n".join(lines)

    def output_path(self, week_label: str) -> Path:
        """出力ファイルパスを返す"""
        return self._reports_dir / f"{week_label}.md"

    def save(self, report: WeeklyReport) -> Path:
        """レポートをファイルに保存する"""
        content = self.render(report)
        path = self.output_path(report.analysis.week_label)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        logger.info("Report saved to %s", path)
        return path

    @staticmethod
    def build_report(
        analysis: WeeklyAnalysis,
        *,
        model: str = "gemini-2.5-flash",
    ) -> WeeklyReport:
        """WeeklyAnalysis から WeeklyReport を構築する"""
        return WeeklyReport(
            analysis=analysis,
            generated_at=datetime.now(),
            model=model,
        )
