"""tests for reporter.py"""

from __future__ import annotations

from datetime import date, datetime

from gh_trend_reporter.models import CategoryGroup, WeeklyAnalysis, WeeklyReport
from gh_trend_reporter.reporter import ReportGenerator


def _make_analysis(**kwargs: object) -> WeeklyAnalysis:
    """テスト用の WeeklyAnalysis を生成するヘルパー"""
    defaults: dict[str, object] = {
        "week_label": "2025-W03",
        "period_start": date(2025, 1, 13),
        "period_end": date(2025, 1, 19),
        "total_repos_collected": 50,
        "top_languages": [
            {"language": "Python", "count": 12, "percentage": 24.0},
            {"language": "TypeScript", "count": 9, "percentage": 18.0},
            {"language": "Rust", "count": 7, "percentage": 14.0},
        ],
        "categories": [
            CategoryGroup(
                category="AI/機械学習",
                repos=["google/gemma", "meta/llama"],
                summary_ja="LLM 関連が活発",
            ),
            CategoryGroup(
                category="Web開発",
                repos=["vercel/next.js"],
                summary_ja="React フレームワークが人気",
            ),
        ],
        "highlights": [
            "AI エージェントフレームワークが急増",
            "Rust ツールチェインが注目を集める",
            "LLM のオープンウェイト化が進む",
        ],
        "new_entries": ["new-org/new-repo", "another/fresh-repo"],
        "rising_repos": [
            {"name": "google/gemma", "stars_since": 1234, "reason": "Gemma 2 リリース"}
        ],
        "week_over_week": "先週と比べて AI 関連が増加",
    }
    defaults.update(kwargs)
    return WeeklyAnalysis(**defaults)  # type: ignore[arg-type]


def _make_report(**kwargs: object) -> WeeklyReport:
    """テスト用の WeeklyReport を生成するヘルパー"""
    analysis = _make_analysis()
    return WeeklyReport(
        analysis=kwargs.get("analysis", analysis),  # type: ignore[arg-type]
        generated_at=kwargs.get(  # type: ignore[arg-type]
            "generated_at", datetime(2025, 1, 19, 18, 0, 0)
        ),
        model=kwargs.get("model", "gemini-2.5-flash"),  # type: ignore[arg-type]
    )


class TestReportGenerator:

    def test_render_complete_report(self) -> None:
        """完全な WeeklyReport から正しい Markdown を生成"""
        gen = ReportGenerator()
        report = _make_report()
        md = gen.render(report)

        assert "---" in md
        assert "# GitHub Trending 週次レポート — 2025-W03" in md
        assert "## 今週のハイライト" in md
        assert "## 言語別ランキング" in md
        assert "## カテゴリ別分析" in md
        assert "## 新登場リポジトリ" in md
        assert "## 先週との比較" in md
        assert "*Generated by gh-trend-reporter*" in md

    def test_frontmatter_format(self) -> None:
        """YAML frontmatter が正しいフォーマット"""
        gen = ReportGenerator()
        report = _make_report()
        md = gen.render(report)

        lines = md.split("\n")
        assert lines[0] == "---"
        assert 'week: "2025-W03"' in md
        assert 'period: "2025-01-13 〜 2025-01-19"' in md
        assert 'model: "gemini-2.5-flash"' in md
        assert "total_repos: 50" in md

    def test_language_ranking_table(self) -> None:
        """言語ランキングが Markdown テーブル形式"""
        gen = ReportGenerator()
        report = _make_report()
        md = gen.render(report)

        assert "| 1 | Python | 12 | 24.0% |" in md
        assert "| 2 | TypeScript | 9 | 18.0% |" in md
        assert "| 3 | Rust | 7 | 14.0% |" in md

    def test_category_sections(self) -> None:
        """カテゴリごとにセクションが生成される"""
        gen = ReportGenerator()
        report = _make_report()
        md = gen.render(report)

        assert "### AI/機械学習" in md
        assert "LLM 関連が活発" in md
        assert "### Web開発" in md
        assert "google/gemma" in md

    def test_new_entries_table(self) -> None:
        """新登場リポジトリが Markdown テーブル形式"""
        gen = ReportGenerator()
        report = _make_report()
        md = gen.render(report)

        assert "| new-org/new-repo |" in md
        assert "| another/fresh-repo |" in md

    def test_output_file_naming(self, tmp_path: object) -> None:
        """出力ファイル名が {year}-W{week}.md 形式"""
        from pathlib import Path

        gen = ReportGenerator(reports_dir=Path(str(tmp_path)))
        path = gen.output_path("2025-W03")
        assert path.name == "2025-W03.md"

    def test_no_previous_week_data(self) -> None:
        """前週データがない場合、比較セクションをスキップ"""
        gen = ReportGenerator()
        analysis = _make_analysis(week_over_week="", new_entries=[])
        report = _make_report(analysis=analysis)
        md = gen.render(report)

        assert "## 先週との比較" not in md
        assert "## 新登場リポジトリ" not in md

    def test_save_creates_file(self, tmp_path: object) -> None:
        """save メソッドがファイルを正しく作成する"""
        from pathlib import Path

        gen = ReportGenerator(reports_dir=Path(str(tmp_path)))
        report = _make_report()
        path = gen.save(report)

        assert path.exists()
        content = path.read_text(encoding="utf-8")
        assert "2025-W03" in content

    def test_build_report(self) -> None:
        """build_report が WeeklyReport を正しく構築する"""
        analysis = _make_analysis()
        report = ReportGenerator.build_report(analysis, model="test-model")
        assert report.model == "test-model"
        assert report.analysis.week_label == "2025-W03"
        assert isinstance(report.generated_at, datetime)
